version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

    volumes:
      - .:/app
      - /app/node_modules