kind: Deployment
apiVersion: apps/v1 

metadata:
  name: react-app-deployment
  namespace: react-app

spec: 
  replicas: 2
  selector:
    matchLabels:
      app: react-app
    
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: worlddev162/react-app-chatbot:v1.0.1
          ports:
            - containerPort: 5173
          
